package miReproductor;

import java.awt.Window;

/**
 * @author Pablo Valdivia
 */

public class Ecualizador extends javax.swing.JFrame {

    /**
     * Creates new form Ecualizador
     */
    Inicio inicio;
    int actualPreset; 
    float balance;
    
    public Ecualizador(Inicio ini, int preset, float balance) {
        this.inicio = ini;
        this.actualPreset = preset;
        this.balance = balance;
        
        initComponents();
        setLocationRelativeTo(null);
        this.setVisible(true);
        inicializaSliders();
        jComboBox1.setSelectedIndex(actualPreset);
        jSlider1.setValue((int)(balance*jSlider1.getMaximum()));
        
        inicio.setEnabled(false); 
        ((Window)inicio).setFocusableWindowState(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();
        jSlider4 = new javax.swing.JSlider();
        jSlider5 = new javax.swing.JSlider();
        jSlider6 = new javax.swing.JSlider();
        jSlider7 = new javax.swing.JSlider();
        jSlider8 = new javax.swing.JSlider();
        jSlider9 = new javax.swing.JSlider();
        jSlider10 = new javax.swing.JSlider();
        jSlider11 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSlider12 = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Default", "Classical", "Club", "Dance", "Pop", "Rock", "Techno", "Amp Bass Treble", "Amp Treble", "Personalizado" }));
        jComboBox1.setFocusable(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jSlider1.setMajorTickSpacing(100);
        jSlider1.setMinimum(-100);
        jSlider1.setMinorTickSpacing(20);
        jSlider1.setPaintTicks(true);
        jSlider1.setToolTipText("");
        jSlider1.setValue(0);
        jSlider1.setFocusable(false);
        jSlider1.setOpaque(false);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 112, 20));

        jSlider2.setMajorTickSpacing(100);
        jSlider2.setMinimum(-100);
        jSlider2.setMinorTickSpacing(20);
        jSlider2.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider2.setPaintTicks(true);
        jSlider2.setToolTipText("");
        jSlider2.setValue(0);
        jSlider2.setAutoscrolls(true);
        jSlider2.setFocusable(false);
        jSlider2.setOpaque(false);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });
        getContentPane().add(jSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 12, -1, -1));
        jSlider2.getAccessibleContext().setAccessibleName("");

        jSlider3.setMajorTickSpacing(100);
        jSlider3.setMinimum(-100);
        jSlider3.setMinorTickSpacing(20);
        jSlider3.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider3.setPaintTicks(true);
        jSlider3.setValue(0);
        jSlider3.setFocusable(false);
        jSlider3.setOpaque(false);
        jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider3StateChanged(evt);
            }
        });
        getContentPane().add(jSlider3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jSlider4.setMajorTickSpacing(100);
        jSlider4.setMinimum(-100);
        jSlider4.setMinorTickSpacing(20);
        jSlider4.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider4.setPaintTicks(true);
        jSlider4.setValue(0);
        jSlider4.setFocusable(false);
        jSlider4.setOpaque(false);
        jSlider4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider4StateChanged(evt);
            }
        });
        getContentPane().add(jSlider4, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 12, -1, -1));

        jSlider5.setMajorTickSpacing(100);
        jSlider5.setMinimum(-100);
        jSlider5.setMinorTickSpacing(20);
        jSlider5.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider5.setPaintTicks(true);
        jSlider5.setValue(0);
        jSlider5.setFocusable(false);
        jSlider5.setOpaque(false);
        jSlider5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider5StateChanged(evt);
            }
        });
        getContentPane().add(jSlider5, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 12, -1, -1));

        jSlider6.setMajorTickSpacing(100);
        jSlider6.setMinimum(-100);
        jSlider6.setMinorTickSpacing(20);
        jSlider6.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider6.setPaintTicks(true);
        jSlider6.setValue(0);
        jSlider6.setFocusable(false);
        jSlider6.setOpaque(false);
        jSlider6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider6StateChanged(evt);
            }
        });
        getContentPane().add(jSlider6, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 12, -1, -1));

        jSlider7.setMajorTickSpacing(100);
        jSlider7.setMinimum(-100);
        jSlider7.setMinorTickSpacing(20);
        jSlider7.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider7.setPaintTicks(true);
        jSlider7.setValue(0);
        jSlider7.setFocusable(false);
        jSlider7.setOpaque(false);
        jSlider7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider7StateChanged(evt);
            }
        });
        getContentPane().add(jSlider7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 12, -1, -1));

        jSlider8.setMajorTickSpacing(100);
        jSlider8.setMinimum(-100);
        jSlider8.setMinorTickSpacing(20);
        jSlider8.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider8.setPaintTicks(true);
        jSlider8.setValue(0);
        jSlider8.setFocusable(false);
        jSlider8.setOpaque(false);
        jSlider8.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider8StateChanged(evt);
            }
        });
        getContentPane().add(jSlider8, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 12, -1, -1));

        jSlider9.setMajorTickSpacing(100);
        jSlider9.setMinimum(-100);
        jSlider9.setMinorTickSpacing(20);
        jSlider9.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider9.setPaintTicks(true);
        jSlider9.setValue(0);
        jSlider9.setFocusable(false);
        jSlider9.setOpaque(false);
        jSlider9.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider9StateChanged(evt);
            }
        });
        getContentPane().add(jSlider9, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 12, -1, -1));

        jSlider10.setMajorTickSpacing(100);
        jSlider10.setMinimum(-100);
        jSlider10.setMinorTickSpacing(20);
        jSlider10.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider10.setPaintTicks(true);
        jSlider10.setValue(0);
        jSlider10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSlider10.setFocusable(false);
        jSlider10.setOpaque(false);
        jSlider10.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider10StateChanged(evt);
            }
        });
        getContentPane().add(jSlider10, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 12, -1, -1));

        jSlider11.setMajorTickSpacing(100);
        jSlider11.setMinimum(-100);
        jSlider11.setMinorTickSpacing(20);
        jSlider11.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider11.setPaintTicks(true);
        jSlider11.setValue(0);
        jSlider11.setFocusable(false);
        jSlider11.setOpaque(false);
        jSlider11.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider11StateChanged(evt);
            }
        });
        getContentPane().add(jSlider11, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 12, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 245, 238, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Balance");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 70, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("70");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("180");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 210, 30, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" 320");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 30, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" 600");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 30, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("1k");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 20, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("3k");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("6k");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("12k");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("14k");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("16k");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("+12dB");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("+6dB");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("0dB");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("-6dB");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("-12dB");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo1.jpg"))); // NOI18N
        jLabel18.setToolTipText("");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 500, 310));

        jSlider12.setMajorTickSpacing(100);
        jSlider12.setMinimum(-100);
        jSlider12.setMinorTickSpacing(20);
        jSlider12.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider12.setPaintTicks(true);
        jSlider12.setValue(0);
        jSlider12.setFocusable(false);
        jSlider12.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider12StateChanged(evt);
            }
        });
        getContentPane().add(jSlider12, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 12, -1, -1));

        pack();
    }// </editor-fold>                        

    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        inicio.setEnabled(true); 
        ((Window)inicio).setFocusableWindowState(true);
        this.dispose();
    }                                  

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        switch(jComboBox1.getSelectedIndex()){
            case 0:
                jSlider2.setValue(0); jSlider7.setValue(0);
                jSlider3.setValue(0); jSlider8.setValue(0);
                jSlider4.setValue(0); jSlider9.setValue(0);
                jSlider5.setValue(0); jSlider10.setValue(0);
                jSlider6.setValue(0); jSlider11.setValue(0);
                inicio.actualPreset = 0;
                break;
            case 1:
                jSlider2.setValue(0); jSlider7.setValue(0);
                jSlider3.setValue(0); jSlider8.setValue(-20);
                jSlider4.setValue(0); jSlider9.setValue(-20);
                jSlider5.setValue(0); jSlider10.setValue(-20);
                jSlider6.setValue(0); jSlider11.setValue(-30);
                inicio.actualPreset = 1;
                break;
            case 2:
                jSlider2.setValue(0); jSlider7.setValue(20);
                jSlider3.setValue(0); jSlider8.setValue(10);
                jSlider4.setValue(10); jSlider9.setValue(0);
                jSlider5.setValue(20); jSlider10.setValue(0);
                jSlider6.setValue(20); jSlider11.setValue(0);
                inicio.actualPreset = 2;
                break;
            case 3:
                jSlider2.setValue(30); jSlider7.setValue(-10);
                jSlider3.setValue(20); jSlider8.setValue(-20);
                jSlider4.setValue(10); jSlider9.setValue(-20);
                jSlider5.setValue(0); jSlider10.setValue(0);
                jSlider6.setValue(0); jSlider11.setValue(0);
                inicio.actualPreset = 3;
                break;
            case 4:
                jSlider2.setValue(-5); jSlider7.setValue(-10);
                jSlider3.setValue(10); jSlider8.setValue(-10);
                jSlider4.setValue(20); jSlider9.setValue(-10);
                jSlider5.setValue(25); jSlider10.setValue(-5);
                jSlider6.setValue(10); jSlider11.setValue(-5);
                inicio.actualPreset = 4;
                break;
            case 5:
                jSlider2.setValue(32); jSlider7.setValue(10);
                jSlider3.setValue(25); jSlider8.setValue(25);
                jSlider4.setValue(-30); jSlider9.setValue(30);
                jSlider5.setValue(-40); jSlider10.setValue(30);
                jSlider6.setValue(-15); jSlider11.setValue(30);
                inicio.actualPreset = 5;
                break;
            case 6:
                jSlider2.setValue(30); jSlider7.setValue(0);
                jSlider3.setValue(25); jSlider8.setValue(20);
                jSlider4.setValue(0); jSlider9.setValue(30);
                jSlider5.setValue(-20); jSlider10.setValue(24);
                jSlider6.setValue(-20); jSlider11.setValue(20);
                inicio.actualPreset = 6;
                break;
            case 7:
                jSlider2.setValue(20); jSlider7.setValue(0);
                jSlider3.setValue(20); jSlider8.setValue(30);
                jSlider4.setValue(0); jSlider9.setValue(60);
                jSlider5.setValue(-30); jSlider10.setValue(70);
                jSlider6.setValue(-10); jSlider11.setValue(70);
                inicio.actualPreset = 7;
                break;
            case 8:
                jSlider2.setValue(-80); jSlider7.setValue(50);
                jSlider3.setValue(-80); jSlider8.setValue(90);
                jSlider4.setValue(-80); jSlider9.setValue(90);
                jSlider5.setValue(-20); jSlider10.setValue(90);
                jSlider6.setValue(10); jSlider11.setValue(90);
                inicio.actualPreset = 8;
                break;
            case 9:
                jSlider2.setValue(inicio.eqPersonalizado[0]);
                jSlider3.setValue(inicio.eqPersonalizado[1]);
                jSlider4.setValue(inicio.eqPersonalizado[2]);
                jSlider5.setValue(inicio.eqPersonalizado[3]);
                jSlider6.setValue(inicio.eqPersonalizado[4]);
                jSlider7.setValue(inicio.eqPersonalizado[5]);
                jSlider8.setValue(inicio.eqPersonalizado[6]);
                jSlider9.setValue(inicio.eqPersonalizado[7]);
                jSlider10.setValue(inicio.eqPersonalizado[8]);
                jSlider11.setValue(inicio.eqPersonalizado[9]);
                inicio.actualPreset = 9;
                break;
        }
    }                                          

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {                                      
        inicio.eqFloat[0]=(float)jSlider2.getValue()/jSlider2.getMaximum();
        if(jComboBox1.getSelectedIndex() == 9){
            inicio.eqPersonalizado[0]=jSlider2.getValue();
            inicio.actualPreset = 9;
        }
    }                                     

    private void jSlider4StateChanged(javax.swing.event.ChangeEvent evt) {                                      
        inicio.eqFloat[2]=(float)jSlider4.getValue()/jSlider4.getMaximum();
        if(jComboBox1.getSelectedIndex() == 9){
            inicio.eqPersonalizado[2]=jSlider4.getValue();
            inicio.actualPreset = 9;
        }
    }                                     

    private void jSlider5StateChanged(javax.swing.event.ChangeEvent evt) {                                      
        inicio.eqFloat[3]=(float)jSlider5.getValue()/jSlider5.getMaximum();
        if(jComboBox1.getSelectedIndex() == 9){
            inicio.eqPersonalizado[3]=jSlider5.getValue();
            inicio.actualPreset = 9;
        }
    }                                     

    private void jSlider6StateChanged(javax.swing.event.ChangeEvent evt) {                                      
        inicio.eqFloat[4]=(float)jSlider6.getValue()/jSlider6.getMaximum();
        if(jComboBox1.getSelectedIndex() == 9){
            inicio.eqPersonalizado[4]=jSlider6.getValue();
            inicio.actualPreset = 9;
        }
    }                                     

    private void jSlider7StateChanged(javax.swing.event.ChangeEvent evt) {                                      
        inicio.eqFloat[5]=(float)jSlider7.getValue()/jSlider7.getMaximum();
        if(jComboBox1.getSelectedIndex() == 9){
            inicio.eqPersonalizado[5]=jSlider7.getValue();
            inicio.actualPreset = 9;
        }
    }                                     

    private void jSlider8StateChanged(javax.swing.event.ChangeEvent evt) {                                      
        inicio.eqFloat[6]=(float)jSlider8.getValue()/jSlider8.getMaximum();
        if(jComboBox1.getSelectedIndex() == 9){
            inicio.eqPersonalizado[6]=jSlider8.getValue();
            inicio.actualPreset = 9;
        }
    }                                     

    private void jSlider9StateChanged(javax.swing.event.ChangeEvent evt) {                                      
        inicio.eqFloat[7]=(float)jSlider9.getValue()/jSlider9.getMaximum();
        if(jComboBox1.getSelectedIndex() == 9){
            inicio.eqPersonalizado[7]=jSlider9.getValue();
            inicio.actualPreset = 9;
        }
    }                                     

    private void jSlider10StateChanged(javax.swing.event.ChangeEvent evt) {                                       
        inicio.eqFloat[8]=(float)jSlider10.getValue()/jSlider10.getMaximum();
        if(jComboBox1.getSelectedIndex() == 9){
            inicio.eqPersonalizado[8]=jSlider10.getValue();
            inicio.actualPreset = 9;
        }
    }                                      

    private void jSlider11StateChanged(javax.swing.event.ChangeEvent evt) {                                       
        inicio.eqFloat[9]=(float)jSlider11.getValue()/jSlider11.getMaximum();
        if(jComboBox1.getSelectedIndex() == 9){
            inicio.eqPersonalizado[9]=jSlider11.getValue();
            inicio.actualPreset = 9;
        }
    }                                      

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {                                      
        inicio.myReproductorAudio.Balance((float)jSlider1.getValue()/jSlider1.getMaximum());
    }                                     

    private void jSlider12StateChanged(javax.swing.event.ChangeEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void jSlider3StateChanged(javax.swing.event.ChangeEvent evt) {                                      
        inicio.eqFloat[1]=(float)jSlider3.getValue()/jSlider3.getMaximum();
        if(jComboBox1.getSelectedIndex() == 9){
            inicio.eqPersonalizado[1]=jSlider3.getValue();
            inicio.actualPreset = 9;
        }
    }                                     

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider10;
    private javax.swing.JSlider jSlider11;
    private javax.swing.JSlider jSlider12;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSlider5;
    private javax.swing.JSlider jSlider6;
    private javax.swing.JSlider jSlider7;
    private javax.swing.JSlider jSlider8;
    private javax.swing.JSlider jSlider9;
    // End of variables declaration                   

    void inicializaSliders(){
        jSlider2.setValue((int)((Inicio.eqFloat[0])*jSlider2.getMaximum()));
        jSlider3.setValue((int)((Inicio.eqFloat[1])*jSlider3.getMaximum()));
        jSlider4.setValue((int)((Inicio.eqFloat[2])*jSlider4.getMaximum()));
        jSlider5.setValue((int)((Inicio.eqFloat[3])*jSlider5.getMaximum()));
        jSlider6.setValue((int)((Inicio.eqFloat[4])*jSlider6.getMaximum()));
        jSlider7.setValue((int)((Inicio.eqFloat[5])*jSlider7.getMaximum()));
        jSlider8.setValue((int)((Inicio.eqFloat[6])*jSlider8.getMaximum()));
        jSlider9.setValue((int)((Inicio.eqFloat[7])*jSlider9.getMaximum()));
        jSlider10.setValue((int)((Inicio.eqFloat[8])*jSlider10.getMaximum()));
        jSlider11.setValue((int)((Inicio.eqFloat[9])*jSlider11.getMaximum()));
    }
}


